import { ColorType } from "./types";

const API_URI = "api";

const COLORS: ColorType[] = ['#DB3333', '#DB6F33', '#DBC033', '#69DB33', '#33DB9E', '#33C7DB', '#3376DB', '#3633DB', '#7D33DB', '#D833DB'];

const SEND_ARRAY_ERROR = "SEND_ARRAY_ERROR";
const SEND_ARRAY_REQUEST = "SEND_ARRAY_REQUEST";
const SEND_ARRAY_SUCCESS = "SEND_ARRAY_SUCCESS";

export {API_URI, COLORS, SEND_ARRAY_ERROR, SEND_ARRAY_REQUEST, SEND_ARRAY_SUCCESS };